diagram_fact(as, cell_10, "geometry").
diagram_fact(as, cell_11, "geometry").
diagram_fact(as, cell_12, "geometry").
diagram_fact(as, cell_13, "geometry").
diagram_fact(as, cell_14, "geometry").
diagram_fact(as, cell_15, "geometry").
diagram_fact(as, cell_16, "geometry").
diagram_fact(as, cell_17, "geometry").
diagram_fact(as, cell_18, "geometry").
diagram_fact(as, cell_19, "geometry").
diagram_fact(as, cell_20, "geometry").
diagram_fact(as, cell_6, "geometry").
diagram_fact(as, cell_7, "geometry").
diagram_fact(as, cell_8, "geometry").
diagram_fact(as, cell_9, "geometry").
diagram_fact(aspect, cell_10, "fixed").
diagram_fact(aspect, cell_12, "fixed").
diagram_fact(aspect, cell_13, "fixed").
diagram_fact(aspect, cell_14, "fixed").
diagram_fact(aspect, cell_15, "fixed").
diagram_fact(aspect, cell_19, "fixed").
diagram_fact(aspect, cell_20, "fixed").
diagram_fact(aspect, cell_8, "fixed").
diagram_fact(cell, cell_10, "").
diagram_fact(cell, cell_11, "").
diagram_fact(cell, cell_12, "").
diagram_fact(cell, cell_13, "").
diagram_fact(cell, cell_14, "").
diagram_fact(cell, cell_15, "").
diagram_fact(cell, cell_16, "").
diagram_fact(cell, cell_17, "").
diagram_fact(cell, cell_18, "").
diagram_fact(cell, cell_19, "").
diagram_fact(cell, cell_20, "").
diagram_fact(cell, cell_4, "").
diagram_fact(cell, cell_5, "").
diagram_fact(cell, cell_6, "").
diagram_fact(cell, cell_7, "").
diagram_fact(cell, cell_8, "").
diagram_fact(cell, cell_9, "").
diagram_fact(curved, cell_9, 1).
diagram_fact(diagram, diagram_1, "").
diagram_fact(edge, cell_16, 1).
diagram_fact(edge, cell_17, 1).
diagram_fact(edge, cell_18, 1).
diagram_fact(edge, cell_9, 1).
diagram_fact(edgeStyle, cell_18, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_9, "orthogonalEdgeStyle").
diagram_fact(endArrow, cell_16, "classic").
diagram_fact(endArrow, cell_17, "classic").
diagram_fact(entryDx, cell_17, 0).
diagram_fact(entryDx, cell_18, 0).
diagram_fact(entryDx, cell_9, 0).
diagram_fact(entryDy, cell_17, 0).
diagram_fact(entryDy, cell_18, 0).
diagram_fact(entryDy, cell_9, 0).
diagram_fact(entryX, cell_17, 0).
diagram_fact(entryX, cell_18, 0).
diagram_fact(entryX, cell_9, 0).
diagram_fact(entryY, cell_17, 0.5).
diagram_fact(entryY, cell_18, 0.5).
diagram_fact(entryY, cell_9, 0.5).
diagram_fact(exitDx, cell_16, 0).
diagram_fact(exitDx, cell_17, 0).
diagram_fact(exitDx, cell_18, 0).
diagram_fact(exitDx, cell_9, 0).
diagram_fact(exitDy, cell_16, 0).
diagram_fact(exitDy, cell_17, 0).
diagram_fact(exitDy, cell_18, 0).
diagram_fact(exitDy, cell_9, 0).
diagram_fact(exitX, cell_16, 1).
diagram_fact(exitX, cell_17, 1).
diagram_fact(exitX, cell_18, 1).
diagram_fact(exitX, cell_9, 1).
diagram_fact(exitY, cell_16, 0.5).
diagram_fact(exitY, cell_17, 0.5).
diagram_fact(exitY, cell_18, 0.5).
diagram_fact(exitY, cell_9, 0.5).
diagram_fact(fillColor, cell_10, "#fff2cc").
diagram_fact(fillColor, cell_12, "#d5e8d4").
diagram_fact(fillColor, cell_13, "#fff2cc").
diagram_fact(fillColor, cell_14, "#fff2cc").
diagram_fact(fillColor, cell_15, "#fff2cc").
diagram_fact(fillColor, cell_19, "#d5e8d4").
diagram_fact(fillColor, cell_20, "#fff2cc").
diagram_fact(fillColor, cell_6, "#ffffff").
diagram_fact(fillColor, cell_8, "#d5e8d4").
diagram_fact(fontColor, cell_17, "#82B366").
diagram_fact(fontColor, cell_18, "#82B366").
diagram_fact(fontColor, cell_6, "#82B366").
diagram_fact(fontStyle, cell_10, 0).
diagram_fact(fontStyle, cell_12, 0).
diagram_fact(fontStyle, cell_13, 0).
diagram_fact(fontStyle, cell_14, 0).
diagram_fact(fontStyle, cell_15, 0).
diagram_fact(fontStyle, cell_19, 0).
diagram_fact(fontStyle, cell_20, 0).
diagram_fact(fontStyle, cell_8, 0).
diagram_fact(height, cell_10, 40).
diagram_fact(height, cell_11, 140).
diagram_fact(height, cell_12, 40).
diagram_fact(height, cell_13, 40).
diagram_fact(height, cell_14, 40).
diagram_fact(height, cell_15, 40).
diagram_fact(height, cell_16, 50).
diagram_fact(height, cell_17, 50).
diagram_fact(height, cell_19, 40).
diagram_fact(height, cell_20, 40).
diagram_fact(height, cell_6, 235).
diagram_fact(height, cell_7, 140).
diagram_fact(height, cell_8, 40).
diagram_fact(html, cell_10, 1).
diagram_fact(html, cell_11, 1).
diagram_fact(html, cell_12, 1).
diagram_fact(html, cell_13, 1).
diagram_fact(html, cell_14, 1).
diagram_fact(html, cell_15, 1).
diagram_fact(html, cell_16, 1).
diagram_fact(html, cell_17, 1).
diagram_fact(html, cell_18, 1).
diagram_fact(html, cell_19, 1).
diagram_fact(html, cell_20, 1).
diagram_fact(html, cell_6, 1).
diagram_fact(html, cell_7, 1).
diagram_fact(html, cell_8, 1).
diagram_fact(html, cell_9, 1).
diagram_fact(jettySize, cell_18, "auto").
diagram_fact(jettySize, cell_9, "auto").
diagram_fact(kind, cell_10, "ellipse").
diagram_fact(kind, cell_12, "ellipse").
diagram_fact(kind, cell_13, "ellipse").
diagram_fact(kind, cell_14, "ellipse").
diagram_fact(kind, cell_15, "ellipse").
diagram_fact(kind, cell_19, "ellipse").
diagram_fact(kind, cell_20, "ellipse").
diagram_fact(kind, cell_8, "ellipse").
diagram_fact(mxGraphModel, mxGraphModel_2, mxGraphModel_2).
diagram_fact(name, diagram_1, "Daisy Chain").
diagram_fact(orthogonalLoop, cell_18, 1).
diagram_fact(orthogonalLoop, cell_9, 1).
diagram_fact(parent, cell_10, id_1).
diagram_fact(parent, cell_11, id_1).
diagram_fact(parent, cell_12, id_1).
diagram_fact(parent, cell_13, id_1).
diagram_fact(parent, cell_14, id_1).
diagram_fact(parent, cell_15, id_1).
diagram_fact(parent, cell_16, id_1).
diagram_fact(parent, cell_17, id_1).
diagram_fact(parent, cell_18, id_1).
diagram_fact(parent, cell_19, id_1).
diagram_fact(parent, cell_20, id_1).
diagram_fact(parent, cell_5, id_0).
diagram_fact(parent, cell_6, id_1).
diagram_fact(parent, cell_7, id_1).
diagram_fact(parent, cell_8, id_1).
diagram_fact(parent, cell_9, id_1).
diagram_fact(relative, cell_16, 1).
diagram_fact(relative, cell_17, 1).
diagram_fact(relative, cell_18, 1).
diagram_fact(relative, cell_9, 1).
diagram_fact(root, root_3, root_3).
diagram_fact(rounded, cell_11, 1).
diagram_fact(rounded, cell_17, 0).
diagram_fact(rounded, cell_18, 0).
diagram_fact(rounded, cell_6, 1).
diagram_fact(rounded, cell_7, 1).
diagram_fact(source, cell_16, id_YGWi19lw0HMaLNqbiAeP__11).
diagram_fact(source, cell_17, id_YGWi19lw0HMaLNqbiAeP__10).
diagram_fact(source, cell_18, id_YGWi19lw0HMaLNqbiAeP__15).
diagram_fact(source, cell_9, id_YGWi19lw0HMaLNqbiAeP__6).
diagram_fact(strokeColor, cell_10, "#d6b656").
diagram_fact(strokeColor, cell_12, "#82b366").
diagram_fact(strokeColor, cell_13, "#d6b656").
diagram_fact(strokeColor, cell_14, "#d6b656").
diagram_fact(strokeColor, cell_15, "#d6b656").
diagram_fact(strokeColor, cell_19, "#82b366").
diagram_fact(strokeColor, cell_20, "#d6b656").
diagram_fact(strokeColor, cell_8, "#82b366").
diagram_fact(synonym, cell_10, id_YGWi19lw0HMaLNqbiAeP__6).
diagram_fact(synonym, cell_11, id_YGWi19lw0HMaLNqbiAeP__7).
diagram_fact(synonym, cell_12, id_YGWi19lw0HMaLNqbiAeP__8).
diagram_fact(synonym, cell_13, id_YGWi19lw0HMaLNqbiAeP__9).
diagram_fact(synonym, cell_14, id_YGWi19lw0HMaLNqbiAeP__10).
diagram_fact(synonym, cell_15, id_YGWi19lw0HMaLNqbiAeP__11).
diagram_fact(synonym, cell_16, id_YGWi19lw0HMaLNqbiAeP__12).
diagram_fact(synonym, cell_17, id_YGWi19lw0HMaLNqbiAeP__13).
diagram_fact(synonym, cell_18, id_YGWi19lw0HMaLNqbiAeP__14).
diagram_fact(synonym, cell_19, id_YGWi19lw0HMaLNqbiAeP__15).
diagram_fact(synonym, cell_20, id_YGWi19lw0HMaLNqbiAeP__16).
diagram_fact(synonym, cell_4, id_0).
diagram_fact(synonym, cell_5, id_1).
diagram_fact(synonym, cell_6, id_YGWi19lw0HMaLNqbiAeP__1).
diagram_fact(synonym, cell_7, id_YGWi19lw0HMaLNqbiAeP__3).
diagram_fact(synonym, cell_8, id_YGWi19lw0HMaLNqbiAeP__4).
diagram_fact(synonym, cell_9, id_YGWi19lw0HMaLNqbiAeP__5).
diagram_fact(target, cell_17, id_YGWi19lw0HMaLNqbiAeP__16).
diagram_fact(target, cell_18, id_YGWi19lw0HMaLNqbiAeP__4).
diagram_fact(target, cell_9, id_YGWi19lw0HMaLNqbiAeP__8).
diagram_fact(value, cell_10, "Pass").
diagram_fact(value, cell_11, "G").
diagram_fact(value, cell_12, "X").
diagram_fact(value, cell_13, "Pass").
diagram_fact(value, cell_14, "Result").
diagram_fact(value, cell_15, "Result").
diagram_fact(value, cell_16, "").
diagram_fact(value, cell_17, "").
diagram_fact(value, cell_19, "X").
diagram_fact(value, cell_20, "Result").
diagram_fact(value, cell_6, "").
diagram_fact(value, cell_7, "F").
diagram_fact(value, cell_8, "X").
diagram_fact(vertex, cell_10, 1).
diagram_fact(vertex, cell_11, 1).
diagram_fact(vertex, cell_12, 1).
diagram_fact(vertex, cell_13, 1).
diagram_fact(vertex, cell_14, 1).
diagram_fact(vertex, cell_15, 1).
diagram_fact(vertex, cell_19, 1).
diagram_fact(vertex, cell_20, 1).
diagram_fact(vertex, cell_6, 1).
diagram_fact(vertex, cell_7, 1).
diagram_fact(vertex, cell_8, 1).
diagram_fact(whiteSpace, cell_10, "wrap").
diagram_fact(whiteSpace, cell_11, "wrap").
diagram_fact(whiteSpace, cell_12, "wrap").
diagram_fact(whiteSpace, cell_13, "wrap").
diagram_fact(whiteSpace, cell_14, "wrap").
diagram_fact(whiteSpace, cell_15, "wrap").
diagram_fact(whiteSpace, cell_19, "wrap").
diagram_fact(whiteSpace, cell_20, "wrap").
diagram_fact(whiteSpace, cell_6, "wrap").
diagram_fact(whiteSpace, cell_7, "wrap").
diagram_fact(whiteSpace, cell_8, "wrap").
diagram_fact(width, cell_10, 40).
diagram_fact(width, cell_11, 120).
diagram_fact(width, cell_12, 40).
diagram_fact(width, cell_13, 40).
diagram_fact(width, cell_14, 40).
diagram_fact(width, cell_15, 40).
diagram_fact(width, cell_16, 50).
diagram_fact(width, cell_17, 50).
diagram_fact(width, cell_19, 40).
diagram_fact(width, cell_20, 40).
diagram_fact(width, cell_6, 630).
diagram_fact(width, cell_7, 125).
diagram_fact(width, cell_8, 40).
diagram_fact(x, cell_10, 295).
diagram_fact(x, cell_11, 455).
diagram_fact(x, cell_12, 435).
diagram_fact(x, cell_13, 555).
diagram_fact(x, cell_14, 295).
diagram_fact(x, cell_15, 555).
diagram_fact(x, cell_19, 65).
diagram_fact(x, cell_20, 695).
diagram_fact(x, cell_6, 85).
diagram_fact(x, cell_7, 190).
diagram_fact(x, cell_8, 170).
diagram_fact(y, cell_10, 1020).
diagram_fact(y, cell_11, 995).
diagram_fact(y, cell_12, 1020).
diagram_fact(y, cell_13, 1020).
diagram_fact(y, cell_14, 1070).
diagram_fact(y, cell_15, 1070).
diagram_fact(y, cell_19, 1020).
diagram_fact(y, cell_20, 1070).
diagram_fact(y, cell_6, 960).
diagram_fact(y, cell_7, 995).
diagram_fact(y, cell_8, 1020).
